# Generated by Django 5.0.6 on 2024-07-01 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(null=True)),
                ('url', models.CharField(max_length=1024)),
                ('number_of_entries', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.table')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.AddField(
            model_name='table',
            name='tags',
            field=models.ManyToManyField(to='core.tag'),
        ),
    ]
