# Generated by Django 5.0.6 on 2024-07-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
