# Generated by Django 5.0.6 on 2024-07-03 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.telegramchat'),
        ),
        migrations.AlterField(
            model_name='table',
            name='url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
