# Generated by Django 5.0.6 on 2024-07-02 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_table_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='table',
            name='number_of_entries',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
