# Generated by Django 5.0.6 on 2024-07-03 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_table_author_alter_table_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.telegramchat'),
        ),
    ]
