# Generated by Django 5.0.6 on 2024-06-28 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_entry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.table'),
        ),
    ]
