# Generated by Django 5.0.6 on 2024-06-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_entry_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='short_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
