# Generated by Django 5.0.6 on 2024-06-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_table_short_name_alter_table_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='tags',
            field=models.ManyToManyField(null=True, to='core.tag'),
        ),
    ]
