# Generated by Django 5.0.6 on 2024-06-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_table_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='tags',
            field=models.ManyToManyField(to='core.tag'),
        ),
    ]
