# Generated by Django 5.0.6 on 2024-07-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_table_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='short_name',
        ),
    ]
