version: "3.9"

services:
  web:
    restart: always
    build: 
      context: ./src
    ports: 
      - "8000:8000"
    command: python ./app/manage.py runserver 0.0.0.0:8000

  bot:
    restart: always
    build: 
      context: ./src
    command: python ./app/manage.py runbot